#!/bin/bash
#script fu  sion
# Version 1

clear

erreur(){
	echo
	echo -e '\033[4;33;1msyntax:\033[0m'
	echo -e '\033[3;32;1m fu\033[1;37;1m [DossierVideoHD] [DossierVideoSD] \033[0m'
}

validarg(){
	if [ ! -d "$1" ]; then
		echo "le dossier "$1" de  destination  n'existe pas :"
		erreur
		exit
	fi
}

#fichiertolist(){
#echo  $1 
#$2
#$1=.
#echo  $1
#	for fichier in $1*; do listeHD+=($fichier); done
#}

if [ "$#" = "0" ]; then
	echo pas dargument
	erreur
else
	validarg $1
	validarg $2
	for fichier in $1*; do listeHD+=("$fichier"); done
	for fichier in $2*; do listeSD+=("$fichier"); done

	#fichiertolist $1 listeHD
	#fichiertolist $2 listeSD
	
	#fichier a  covertire

	#echo ${listeHD[*]}
	#echo ${listeSD[*]}

	output="$(echo $1|tr -d /)"
	mkdir "$output.OUT"
#libopus	
	for parcoure in ${!listeHD[@]}; do ffmpeg -i "${listeHD[parcoure]}" -i "${listeSD[parcoure]}" -map 0 -map 1 -map -1:v -metadata title="$output $((1+$parcoure))" -metadata description="audio transcodée... thank to ffmpeg" -codec:v copy  -codec:a libopus "$output.OUT/$output $((1+$parcoure)).mkv"; done
	
fi
